storage: ~/storage/
turn_off_command: ''
render_size:
  x: 900
  y: 550
roi:
  x: 600
  y: 950
  width: 1800
  height: 1100
gui:
  cooling:
    buttons:
    - - - '-20'
        - -20.0
      - - '-15'
        - -15.0
      - - '-10'
        - -10.0
      - - '-5'
        - -5.0
    - - - '0'
        - 0.0
      - - '5'
        - 5.0
      - - '10'
        - 10.0
      - - '15'
        - 15.0
    - - - '20'
        - 20.0
      - - '25'
        - 25.0
  heating:
    buttons:
    - - - '-20'
        - -20.0
      - - '-15'
        - -15.0
      - - '-10'
        - -10.0
      - - '-5'
        - -5.0
    - - - '0'
        - 0.0
      - - '5'
        - 5.0
      - - '10'
        - 10.0
      - - '15'
        - 15.0
    - - - '20'
        - 20.0
      - - '25'
        - 25.0
  exposure:
    buttons:
    - - - '1 ms'
        - 0.001
      - - '10 ms'
        - 0.01
      - - '20 ms'
        - 0.02
      - - '50 ms'
        - 0.05
    - - - '100 ms'
        - 0.1
      - - '200 ms'
        - 0.2
      - - '500 ms'
        - 0.5
      - - '800 ms'
        - 0.8
    - - - ' 1 s'
        - 1
      - - ' 2 s'
        - 2
      - - ' 5 s'
        - 5
      - - '10 s'
        - 10

  gain:
    buttons: []
  histogram_width: 512
  histogram_height: 100
io:
  trigger_input: /sys/class/gpio/gpio17/value
  exposure_status: /sys/class/gpio/gpio2/value
  heating_pwm: /sys/class/gpio/gpio4/value
  main_status: /sys/class/gpio/gpio3/value