storage: ~/storage/
turn_off_command: ''
render_size:
  x: 900
  y: 600
roi:
  x: 0
  y: 0
  width: 0
  height: 0
exp:
  percentile_pix: 0.995
  pixel_tgt: 0.61
  pixel_tol: 0.076
  pixel_exclusion: 100
  min_exopsure:
    secs: 0
    nanos: 32000
  max_exposure:
    secs: 10
    nanos: 0
  max_bin: 1
gui:
  cooling:
    buttons:
    - - text: '-20'
        value: -20.0
      - text: '-15'
        value: -15.0
      - text: '-10'
        value: -10.0
      - text: '-5'
        value: -5.0
    - - text: '0'
        value: 0.0
      - text: '5'
        value: 5.0
      - text: '10'
        value: 10.0
      - text: '15'
        value: 15.0
    - - text: '20'
        value: 20.0
      - text: '25'
        value: 25.0
  heating:
    buttons:
    - - text: '-20'
        value: -20.0
      - text: '-15'
        value: -15.0
      - text: '-10'
        value: -10.0
      - text: '-5'
        value: -5.0
    - - text: '0'
        value: 0.0
      - text: '5'
        value: 5.0
      - text: '10'
        value: 10.0
      - text: '15'
        value: 15.0
    - - text: '20'
        value: 20.0
      - text: '25'
        value: 25.0
  exposure:
    buttons: []
  gain:
    buttons: []
  histogram_width: 512
  histogram_height: 100
io:
  trigger_input: /sys/class/gpio/gpio17/value
  exposure_status: /sys/class/gpio/gpio2/value
  heating_pwm: /sys/class/gpio/gpio4/value
  main_status: /sys/class/gpio/gpio3/value
