[package]
name = "ccdi-imager-demo"
version = "0.1.0"
authors = ["vchvatal"]
edition = "2021"

[dependencies]
cameraunit = "5.1"
image = "0.25"
log = "0.4"

ccdi-imager-interface = { path = "../ccdi-imager-interface" }
ccdi-common = { path = "../ccdi-common" }
