[package]
name = "ccdi-imager-demo"
version = "0.1.0"
authors = ["vchvatal"]
edition = "2021"

[dependencies]
cameraunit = "3.0.0"
image = "0.24.7"
log = "0.4.17"

ccdi-imager-interface = { path = "../ccdi-imager-interface" }
ccdi-common = { path = "../ccdi-common" }
