[package]
name = "ccdi-web-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
yew = { version = "0.20", features = ["csr"] }
yew-websocket = "1.0.0"
gloo = "0.8.0"
gloo-timers = "0.2.6"

ccdi-common = { path = "../ccdi-common" }