[package]
name = "ccdi-imager-moravian"
version = "0.1.0"
authors = ["vchvatal"]
edition = "2021"

[dependencies]
log = "0.4.17"

ccdi-imager-interface = { path = "../ccdi-imager-interface" }
ccdi-driver-moravian = { path = "../ccdi-driver-moravian" }
ccdi-common = { path = "../ccdi-common" }